config/routes.rb
ReviewApp::Application.routes.draw do
  get "dashboard/index"
  get "categories/index"
  devise_for :users
  root 'home#index'
  resources :users, :categories
  resources :books do
    resources :comments
    collection do
      get 'news'        => 'books#news'
      get 'likes/:id'   => 'books#like',    as: :likes
      get 'unlike/:id'  => 'books#unlike',  as: :unlikes
    end

    resources :reviews
  end
  

  namespace :admin do 
    root 'dashboard#index'
    resources :books, :categories
    resources :users do
      collection do 
        get 'admin'
        get 'visitor'
        get 'reviewer'
      end
    end
  end

  namespace :reviewer do 
    root 'dashboard#index'
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_one   :category_book
  has_one   :category, through: :category_book
  has_many  :reviews

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/:style/missing.png" #/images/:style/missing.png
  scope :featured,  -> { where(featured: true) }
  paginates_per 9
  acts_as_commentable
  scope :news,  -> { where("date_release > ?", Time.now) }
  acts_as_votable
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!, :admin?
  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params.merge(category:category_params))
    respond_to do |format|
      if @book.save
        format.html { redirect_to root_path }
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
      else
        #format.html { render action: "new" }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  def admin?
    redirect_to root_path unless current_user.role == "admin"
  end
  private
    def book_params
      params.require(:book).permit(:name,:date_release,:photo,:description,:number_of_page,:author)
    end
    def category_params
      cat_id = params.require(:book).permit(:category)
      Category.find_by_id cat_id[:category]
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :review,:like,:unlike]
  def index
    @user = User.new
    @books = Book.order(:name).page params[:page]
  end
  def new
    @book = Book.new
  end

  def create
    #@book = Task.new(params[:book])
    @book = Book.new(params[:book])
    respond_to do |format|
      if @book.save
        format.html { redirect_to root_path }
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
      else
        #format.html { render action: "new" }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @user = User.new
    @comment = Comment.new user:current_user
    @liked = @book.likes
  end
  def news
    @user = User.new
    @books = Book.news.order(:name).page params[:page]
  end
  def review
  end
  def like
    @book.liked_by current_user
    respond_to do |format|
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
        format.js { redirect_to root_path }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
    end
  end
  def unlike
    @book.unliked_by current_user
  end
  private
  #   # Use callbacks to share common setup or constraints between actions.
    def set_book
      ##ini untuk mendapatkan id dari url terakhir
      @book = Book.find(params[:id])
    end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def task_params
  #     params.require(:task).permit(:name, :completed)
  #   end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/index.html.erb
<div class="midlePan">
  <a href="<%= new_admin_book_path %>">Add New Book</a>
  <h3>List Of Books</h3>

  <table class="table table-striped">
    <tr>
      <th>No.</th>
      <th>Book Title</th>
      <th>Author</th>
      <th></th>
    </tr>
    <% number = 0 %>
    <% @books.each do |book| %>
    <tr>
      <td><%= number += 1 %>.</td>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td>
        <%= link_to 'Edit', edit_admin_book_path(book), class: "btn btn-xs btn-success" %>
        <%= link_to 'Destroy', admin_book_path(book), class: "btn btn-xs btn-danger", id: "destroy_task" , method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/books/new.html.erb
<% #([:admin, @book], html: {id: "form_book"}) in bisa update %>
<%= form_for(@book, url: admin_books_path, html: {id: "form_book", multipart: true}) do |f| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name, required: true %>
</div>
<div class="field">
  <%= f.label :author %><br />
  <%= f.text_field :author, required: true %>
</div>
<div class="field">
  <%= f.label :number_of_page %><br />
  <%= f.text_field :number_of_page, required: true %>
</div>
<div>
  <%= f.label Category %><br />
  <%= f.collection_select(:category, Category.all, :id, :name) %>
</div>
<div>
  <%= f.label :date_release %><br />
  <%= f.date_field :date_release %>
</div>
<div class="field">
  <%= f.label :description %><br />
  <%= f.text_area :description, required: true %>
</div>
<div>
  <%= f.label :photo %><br />
  <%= f.file_field :photo %>
</div>
<div class="actions">
  <br>
  <%= f.submit %>
</div>
<% end %> 