config/routes.rb
ReviewApp::Application.routes.draw do
  get "dashboard/index"
  get "categories/index"
  devise_for :users
  root 'home#index'
  resources :users, :categories
  resources :books do
    resources :comments
    collection do
      get 'news'        => 'books#news'
      get 'likes/:id'   => 'books#like',    as: :likes
      get 'unlike/:id'  => 'books#unlike',  as: :unlikes
    end

    resources :reviews
  end
  

  namespace :admin do 
    root 'dashboard#index'
    resources :books, :categories
    resources :users do
      collection do 
        get 'admin'
        get 'visitor'
        get 'reviewer'
      end
    end
  end

  namespace :reviewer do 
    root 'dashboard#index'
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_one   :category_book
  has_one   :category, through: :category_book
  has_many  :reviews

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/:style/missing.png" #/images/:style/missing.png
  scope :featured,  -> { where(featured: true) }
  paginates_per 9
  acts_as_commentable
  scope :news,  -> { where("date_release > ?", Time.now) }
  acts_as_votable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_books
  has_many :books, through: :category_books
  # def name_with_initial
  #   "#{:name}"
  # end
end

app/models/category_book.rb
class CategoryBook < ActiveRecord::Base
  belongs_to :book
  belongs_to :category
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  def self.find_comments_by_user(user)
    where(["user_id = ?", user.id]).order("created_at DESC")
  end

  def self.find_comments_for_commentable(commentable_str, commentable_id)
    where(["commentable_type = ? and commentable_id = ?", commentable_str, commentable_id]).order("created_at DESC")
  end

  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end  
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
	def self.save upload
		name = upload['datafile'].original_filename
		directory = "public/tes_upload"
		path = File.join(directory, name)
		File.open(path, "wb") { |file| file.write(upload['datafile'].read)}
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/te.rb
class Te < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments
  has_many :reviews

  scope :admin,     -> { where(role: 'admin') }
  scope :visitor,   -> { where(role: 'visitor') }
  scope :reviewer,  -> { where(role: 'reviewer') }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  acts_as_voter
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :review,:like,:unlike]
  def index
    @user = User.new
    @books = Book.order(:name).page params[:page]
  end
  def new
    @book = Book.new
  end

  def create
    #@book = Task.new(params[:book])
    @book = Book.new(params[:book])
    respond_to do |format|
      if @book.save
        format.html { redirect_to root_path }
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
      else
        #format.html { render action: "new" }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @user = User.new
    @comment = Comment.new user:current_user
    @liked = @book.likes
  end
  def news
    @user = User.new
    @books = Book.news.order(:name).page params[:page]
  end
  def review
  end
  def like
    @book.liked_by current_user
    respond_to do |format|
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
        format.js { redirect_to root_path }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
    end
  end
  def unlike
    @book.unliked_by current_user
  end
  private
  #   # Use callbacks to share common setup or constraints between actions.
    def set_book
      ##ini untuk mendapatkan id dari url terakhir
      @book = Book.find(params[:id])
    end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def task_params
  #     params.require(:task).permit(:name, :completed)
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index 
    @user = User.new
    @categories = Category.all
    @books = Book.limit(6)
    @featured = Book.featured.first
    @review = Review.last(3)
  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @book = Book.find(params[:book_id])
    @review = Review.new
  end
  
  def create
    @book   = Book.find(params[:book_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.book = @book
    respond_to do |format|
      if @review.save
        format.html { redirect_to root_path }
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
      else
        #format.html { render action: "new" }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  private
    def review_params
      params.require(:review).permit(:review)
    end

end

app/controllers/tes_controller.rb
class TesController < ApplicationController
  before_action :set_te, only: [:show, :edit, :update, :destroy]

  # GET /tes
  # GET /tes.json
  def index
    "tes"
    #@tes = Te.all
  end

  # GET /tes/1
  # GET /tes/1.json
  def show
  end

  # GET /tes/new
  def new
    @te = Te.new
  end

  # GET /tes/1/edit
  def edit
  end

  # POST /tes
  # POST /tes.json
  def create
    @te = Te.new(te_params)

    respond_to do |format|
      if @te.save
        format.html { redirect_to @te, notice: 'Te was successfully created.' }
        format.json { render action: 'show', status: :created, location: @te }
      else
        format.html { render action: 'new' }
        format.json { render json: @te.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tes/1
  # PATCH/PUT /tes/1.json
  def update
    respond_to do |format|
      if @te.update(te_params)
        format.html { redirect_to @te, notice: 'Te was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @te.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tes/1
  # DELETE /tes/1.json
  def destroy
    @te.destroy
    respond_to do |format|
      format.html { redirect_to tes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_te
      @te = Te.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def te_params
      params[:te]
    end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
	def index
		#"Hello"
		render :file => 'app/views/uploads/uploadfile.rhtml'
	end
	def uploadFile
		post	= DataFile.save(params[:upload])
		render	:text	=> "File has been uploaded"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tes_helper.rb
module TesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/home/index.html.erb
<div id="wrap">
  <div id="main" class="container clear-top">

    <div id="topPan">
      <div class="logoImage">
        <%= image_tag "logo.png" %> 
      </div>
      <div class="logoTitle">
        Books Review
      </div>
      <div class="clearing">
        &nbsp;
      </div>
      <div class="navBar">
        <nav class="navbar navbar-default" role="navigation">
          <ul class="nav navbar-nav">
            <li class="active">
                <%= link_to "Home", root_path %>
            </li>
            <li>
                <%= link_to "Book Release", news_books_path %>
            </li>
          </ul>
        </nav>
      </div>
      <div class="sign-form">
      <% if user_signed_in? == false %>
        <%= form_for(@user, :as => :user, :url => session_path(:user)) do |f| %>
          <%#= devise_error_messages! %>
          Email: <%= f.email_field :email, :autofocus => true %>
          Password:<%= f.password_field :password %>
          <%= f.submit "Sign in" %>
        <% end %>
       Not a member? <!--<a href="#">Sign Up</a>-->
      <% end %>
    <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Administrator", admin_root_path if current_user.role == "admin"  %>
        <%= link_to "Reviewer", reviewer_root_path if current_user.role == "reviewer"  %>
        |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
        <%= link_to "Sign up,", new_user_registration_path, :class => 'navbar-link'  %>
        <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <a href="#">Forgot Password?</a>
    <% end %>
      </div>
    </div>

    <div id="middlePan">
      <div class="row">
        <div class="col-md-8">

        <h3>Feature</h3>
          <div class="feature">
            <div class="feature-img">
              <a href="<%= books_path %>/feature"><%= image_tag @featured.photo.url %></a> 
            </div>
            <div class="feature-summary">
              <%= @featured.description %>
            </div>
            <div class="clearing"></div>
          </div>

          <h3>Books</h3>
          <div class="books">
          <% @books.each do |book| %>
            <div class="box">
              <a href="<%= books_path%>/<%= book.id %>"> <%= image_tag book.photo.url %> </a>
            </div>
          <% end %>
            <%= link_to "more..", books_path, class: "text-right" %>
            <div class="clearing"></div>
          </div>

          <h3>Category</h3>
          <div class="category">            
              <ul>
              <% @categories.each do |category| %>
                <li>
                <%= link_to category.name, category_path(category) %></li>
              <% end %>
              </ul>
          </div>

        </div>

        <div class="col-md-4">

          <div class="new-review">
            <h3>New Review</h3>
            <% @review.each do |review| %>
              <div class="review">
                <%= image_tag review.book.photo.url %>
                <p>
                  <%= link_to review.book.name, book_path(review.book) %><br/>
                  <small>Reviewed by: <%= review.user.email%></small>
                </p>
              </div>
              <div class="clearing"></div>
            <% end %>
          </div>
          <div class="popular-review">
            <h3>Popular</h3>
            <% 3.times do %>
              <div class="review">
                <%= image_tag 'the_namesake.jpg' %>
                <p>
                  Book Title<br/>
                  <small>Reviewed by: Tony</small>
                </p>
              </div>
              <div class="clearing"></div>
            <% end %>            
          </div>
          <div class="reviewer">
            <!-- #Reviewer -->
          </div>

        </div>
      </div>
    </div>

    <div id="bottomPan">
      <!-- #Bottom Pan -->
    </div>
    
  </div>
</div>
<div class="footer">
  <div class="container">
    <p>&copy; 2013. Akademi Rails.</p>
  </div>
</div>

app/views/reviews/index.html.erb
<div id="wrap">
  <div id="main" class="container clear-top">

    <div id="topPan">
      <div class="logoImage">
        <%= image_tag "logo.png" %> 
      </div>
      <div class="logoTitle">
        Books Review
      </div>
      <div class="clearing">
        &nbsp;
      </div>
      <div class="navBar">
        <nav class="navbar navbar-default" role="navigation">
          <ul class="nav navbar-nav">
            <li class="active">
                <%= link_to "Home", root_path %>
            </li>
            <li>
              <%= link_to "Book Release", news_books_path %>
            </li>
          </ul>
        </nav>
      </div>
      <div class="sign-form">
        <% if user_signed_in? == false %>
        <%= form_for(@user, :as => :user, :url => session_path(:user)) do |f| %>
          <%#= devise_error_messages! %>
          Email: <%= f.email_field :email, :autofocus => true %>
          Password:<%= f.password_field :password %>
          <%= f.submit "Sign in" %>
        <% end %>
        Not a member? <!--<a href="#">Sign Up</a>-->
        <% end %>
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Administrator", admin_root_path if current_user.role == "admin"  %>
          <%= link_to "Reviewer", :class => 'navbar-link' if current_user.role == "reviewer"  %>
          |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
          <%= link_to "Sign up,", new_user_registration_path, :class => 'navbar-link'  %>
          <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <a href="#">Forgot Password?</a>
        <% end %>
      </div>
    </div>
    <div id="middlePan">
      <div style="display: block">
        <p>
          <div class="box">
            <%= image_tag @book.photo.url %>
          </div>
        </p>
        <p>
          <strong>Name:</strong>
          <%= @book.name %>
        </p>
        <p>
          <strong>Author:</strong>
          <%= @book.author %>
        </p>
        
        <p>
          <strong>Date Release:</strong>
          <%= @book.date_release %>
        </p>
        <p>
          <strong>Summary:</strong>
          <%= @book.description %>
        </p>
        <div class="clearing"></div>
        <div class="review-form">
          <h3>Write Review:</h3>  
          <%= form_for([@review], url: book_reviews_path, html: {id: "form_review"}) do |f| %>
            <% if @review.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
                <ul>
                <% @review.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <%= f.label :review %><br />
              <%= f.text_area :review, required: true, size: "100x6" %>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %> 
        </div>
      </div>
    </div>
  </div>
</div>