config/routes.rb
ReviewApp::Application.routes.draw do
  get "dashboard/index"
  get "categories/index"
  devise_for :users
  root 'home#index'
  resources :users, :categories
  resources :books do
    resources :comments
    collection do
      get 'news'        => 'books#news'
      get 'likes/:id'   => 'books#like',    as: :likes
      get 'unlike/:id'  => 'books#unlike',  as: :unlikes
    end

    resources :reviews
  end
  

  namespace :admin do 
    root 'dashboard#index'
    resources :books, :categories
    resources :users do
      collection do 
        get 'admin'
        get 'visitor'
        get 'reviewer'
      end
    end
  end

  namespace :reviewer do 
    root 'dashboard#index'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_books
  has_many :books, through: :category_books
  # def name_with_initial
  #   "#{:name}"
  # end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!, :admin?
  
  def index
    @categories = Category.all
  end

  def new 
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path }
        #format.json { render json: @categoery, status: :created, location: @book }
        #format.js { return render status: 200 }
      else
        format.html { render action: "new" }
        #format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end


  def admin?
    redirect_to root_path unless current_user.role == "admin"
  end
  
  private

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @user = User.new
    cat   = Category.find_by_id params[:id]
    @books = cat.books.order(:name).page params[:page] 
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="midlePan">
  <a href="<%= new_admin_category_path %>">Add New Category</a>
  <h3>List Of Category</h3>
  <table class="table table-striped">
    <tr>
      <th>No.</th>
      <th>Book Title</th>
      <th></th>
    </tr>
    <% number = 0 %>
    <% @categories.each do |category| %>
      <tr>
        <td><%= number += 1 %>.</td>
        <td><%= category.name %></td>
        <td>
          <a href="#">Edit</a> | 
          <a href="#">Delete</a>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/categories/new.html.erb
<%= form_for([:admin, @category], url: admin_categories_path, html: {id: "form_category"}) do |f| %>
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name, required: true %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>  