config/routes.rb
ReviewApp::Application.routes.draw do
  get "dashboard/index"
  get "categories/index"
  devise_for :users
  root 'home#index'
  resources :users, :categories
  resources :books do
    resources :comments
    collection do
      get 'news'        => 'books#news'
      get 'likes/:id'   => 'books#like',    as: :likes
      get 'unlike/:id'  => 'books#unlike',  as: :unlikes
    end

    resources :reviews
  end
  

  namespace :admin do 
    root 'dashboard#index'
    resources :books, :categories
    resources :users do
      collection do 
        get 'admin'
        get 'visitor'
        get 'reviewer'
      end
    end
  end

  namespace :reviewer do 
    root 'dashboard#index'
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_one   :category_book
  has_one   :category, through: :category_book
  has_many  :reviews

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/:style/missing.png" #/images/:style/missing.png
  scope :featured,  -> { where(featured: true) }
  paginates_per 9
  acts_as_commentable
  scope :news,  -> { where("date_release > ?", Time.now) }
  acts_as_votable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_books
  has_many :books, through: :category_books
  # def name_with_initial
  #   "#{:name}"
  # end
end

app/models/category_book.rb
class CategoryBook < ActiveRecord::Base
  belongs_to :book
  belongs_to :category
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  def self.find_comments_by_user(user)
    where(["user_id = ?", user.id]).order("created_at DESC")
  end

  def self.find_comments_for_commentable(commentable_str, commentable_id)
    where(["commentable_type = ? and commentable_id = ?", commentable_str, commentable_id]).order("created_at DESC")
  end

  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end  
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
	def self.save upload
		name = upload['datafile'].original_filename
		directory = "public/tes_upload"
		path = File.join(directory, name)
		File.open(path, "wb") { |file| file.write(upload['datafile'].read)}
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/te.rb
class Te < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments
  has_many :reviews

  scope :admin,     -> { where(role: 'admin') }
  scope :visitor,   -> { where(role: 'visitor') }
  scope :reviewer,  -> { where(role: 'reviewer') }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  acts_as_voter
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!
  def admin
    @admins = User.admin
  end
  def visitor
    @visitors = User.visitor
  end
  def reviewer
    @reviewers = User.reviewer
  end
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path }
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
      else
        format.html { render action: "new" }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  def new
    @role = params[:role]
    @user = User.new
  end
  private
    def user_params
      params.require(:user).permit(:email,:password,:role)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :review,:like,:unlike]
  def index
    @user = User.new
    @books = Book.order(:name).page params[:page]
  end
  def new
    @book = Book.new
  end

  def create
    #@book = Task.new(params[:book])
    @book = Book.new(params[:book])
    respond_to do |format|
      if @book.save
        format.html { redirect_to root_path }
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
      else
        #format.html { render action: "new" }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @user = User.new
    @comment = Comment.new user:current_user
    @liked = @book.likes
  end
  def news
    @user = User.new
    @books = Book.news.order(:name).page params[:page]
  end
  def review
  end
  def like
    @book.liked_by current_user
    respond_to do |format|
        #format.json { render json: @book, status: :created, location: @book }
        #format.js { return render status: 200 }
        format.js { redirect_to root_path }
        #format.json { render json: @book.errors, status: :unprocessable_entity }
    end
  end
  def unlike
    @book.unliked_by current_user
  end
  private
  #   # Use callbacks to share common setup or constraints between actions.
    def set_book
      ##ini untuk mendapatkan id dari url terakhir
      @book = Book.find(params[:id])
    end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def task_params
  #     params.require(:task).permit(:name, :completed)
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index 
    @user = User.new
    @categories = Category.all
    @books = Book.limit(6)
    @featured = Book.featured.first
    @review = Review.last(3)
  end



end

app/controllers/tes_controller.rb
class TesController < ApplicationController
  before_action :set_te, only: [:show, :edit, :update, :destroy]

  # GET /tes
  # GET /tes.json
  def index
    "tes"
    #@tes = Te.all
  end

  # GET /tes/1
  # GET /tes/1.json
  def show
  end

  # GET /tes/new
  def new
    @te = Te.new
  end

  # GET /tes/1/edit
  def edit
  end

  # POST /tes
  # POST /tes.json
  def create
    @te = Te.new(te_params)

    respond_to do |format|
      if @te.save
        format.html { redirect_to @te, notice: 'Te was successfully created.' }
        format.json { render action: 'show', status: :created, location: @te }
      else
        format.html { render action: 'new' }
        format.json { render json: @te.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tes/1
  # PATCH/PUT /tes/1.json
  def update
    respond_to do |format|
      if @te.update(te_params)
        format.html { redirect_to @te, notice: 'Te was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @te.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tes/1
  # DELETE /tes/1.json
  def destroy
    @te.destroy
    respond_to do |format|
      format.html { redirect_to tes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_te
      @te = Te.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def te_params
      params[:te]
    end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
	def index
		#"Hello"
		render :file => 'app/views/uploads/uploadfile.rhtml'
	end
	def uploadFile
		post	= DataFile.save(params[:upload])
		render	:text	=> "File has been uploaded"
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tes_helper.rb
module TesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/admin/users/admin.html.erb
<div class="midlePan">
  <a href="<%= new_admin_user_path %>/?role=admin">Add New Admin</a>
  <h3>List Of Books</h3>
  <table class="table table-striped">
    <tr>
      <th>No.</th>
      <th>Email</th>
      <th></th>
    </tr>
    <% number = 0 %>
    <% @admins.each do |admin| %>
    <tr>
      <td><%= number += 1 %>.</td>
      <td><%= admin.email %></td>
      <td>
        <%= link_to 'Edit', edit_admin_user_path(admin), class: "btn btn-xs btn-success" %>
        <%= link_to 'Destroy', admin_user_path(admin), class: "btn btn-xs btn-danger", id: "destroy_task" , method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/users/new.html.erb
<% #([:admin, @user], html: {id: "form_user"}) in bisa update %>
<%= form_for(@user, url: admin_users_path, html: {id: "form_user"}) do |f| %>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :email %><br />
  <%= f.email_field :email, required: true, :autofocus => true %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password, required: true %>
  <%= f.hidden_field :role, value:@role %>
</div>
<div class="actions">
  <br>
  <%= f.submit %>
</div>
<% end %> 

app/views/admin/users/reviewer.html.erb
<div class="midlePan">
  <a href="<%= new_admin_user_path %>/?role=reviewer">Add New Reviewer</a>
  <h3>List Of Reviewer</h3>
  <table class="table table-striped">
    <tr>
      <th>No.</th>
      <th>Email</th>
      <th></th>
    </tr>
    <% number = 0 %>
    <% @reviewers.each do |reviewer| %>
    <tr>
      <td><%= number += 1 %>.</td>
      <td><%= reviewer.email %></td>
      <td>
        <%= link_to 'Edit', edit_admin_user_path(reviewer), class: "btn btn-xs btn-success" %>
        <%= link_to 'Destroy', admin_user_path(reviewer), class: "btn btn-xs btn-danger", id: "destroy_task" , method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/users/visitor.html.erb
<div class="midlePan">
  <a href="<%= new_admin_user_path %>/?role=visitor">Add New Visitor</a>
  <h3>List Of Visitor</h3>
  <table class="table table-striped">
    <tr>
      <th>No.</th>
      <th>Email</th>
      <th></th>
    </tr>
    <% number = 0 %>
    <% @visitors.each do |visitor| %>
    <tr>
      <td><%= number += 1 %>.</td>
      <td><%= visitor.email %></td>
      <td>
        <%= link_to 'Edit', edit_admin_user_path(visitor), class: "btn btn-xs btn-success" %>
        <%= link_to 'Destroy', admin_user_path(visitor), class: "btn btn-xs btn-danger", id: "destroy_task" , method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </table>
</div>